version: "3.3"

services:
    web:
        image: nginx:latest
#        build: provision/nginx
        depends_on:
          - php
        networks:
          - backend
        ports:
          - "8010:80"
        volumes:
          - .:/var/www/html
          - ./provision/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    php:
        build: provision/php
        container_name: php
        working_dir: /var/www/html
        volumes:
          - .:/var/www/html
          - ./provision/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
          - backend
networks:
  backend:
