version: "3.3"

services:
    web:
        build: provision/apache
        depends_on:
          - php
        networks:
          - backend
        ports:
          - "80:80"
        volumes:
          - .:/var/www/html
    php:
        build: provision/php
        container_name: php
        working_dir: /var/www/html
        user: php
        volumes:
          - .:/var/www/html
          - ./provision/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
          - backend
networks:
  backend:
